routes/web.php
<?php

use App\Http\Controllers\ShowPostController;
use App\Http\Controllers\ShowStreamController;
use App\Http\Controllers\ShowCasinoController;
use App\Http\Controllers\FavouritePostController;
use App\Http\Controllers\FavouriteStreamController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\JackpotTrackerController;
use App\Http\Controllers\LotteryJackpotTrackerController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\TermsAndConditionsController;

use App\Http\Controllers\Dashboard\PostController;
use App\Http\Controllers\Dashboard\CategoryController;
use App\Http\Controllers\Dashboard\StreamController;
use App\Http\Controllers\Dashboard\CasinoController;
use App\Http\Controllers\Dashboard\SlotController;
use App\Http\Controllers\Dashboard\JackpotController;
use App\Http\Controllers\Dashboard\CKEditorController;
use App\Http\Controllers\Dashboard\CommentController;
use App\Http\Controllers\Dashboard\AttachmentController;
use App\Http\Controllers\Dashboard\UserController;

use App\Http\Controllers\Auth\AdminLoginController;
use App\Http\Controllers\Auth\LoginController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['verify' => true]);

Route::get('/', [ShowPostController::class, 'index'])->name('home');

// SHOW SINGLE POST
Route::get('post/{slug}', [ShowPostController::class, 'show'])->name('posts.show');

Route::get('streams', [ShowStreamController::class, 'index'])->name('all-streams');
// SHOW SINGLE STREAM
Route::get('stream/{slug}', [ShowStreamController::class, 'show'])->name('streams.show');

// SORTING ROUTS
Route::get('/sortby/{type}/{ascendance}', [ShowPostController::class, 'sortby'])->where(['type' => '[a-z]+', 'ascendance' => '[a-z]+'])->name('posts.sortby');
Route::get('posts/category/{slug}', [ShowPostController::class, 'category'])->name('posts.category');
Route::get('posts/category/{slug}/sortby/{type}/{ascendance}', [ShowPostController::class, 'category_sortby'])->where(['type' => '[a-z]+', 'ascendance' => '[a-z]+'])->name('posts.category.sortby');
Route::get('streams/category/{slug}', [ShowStreamController::class, 'category'])->name('streams.category');

Route::middleware(['verified'])->prefix('favourite')->group(function() {
    Route::get('posts', [FavouritePostController::class, 'index'])->name('favourite.posts.index');
    Route::get('streams', [FavouriteStreamController::class, 'index'])->name('favourite.streams.index');
    Route::post('/save/post/{postid}', [FavouritePostController::class, 'store'])->name('favourite.posts.store');
    Route::post('/save/stream/{postid}', [FavouriteStreamController::class, 'store'])->name('favourite.streams.store');
    Route::post('/destroy/post/{postid}', [FavouritePostController::class, 'destroy'])->name('favourite.posts.destroy');
    Route::post('/destroy/stream/{postid}', [FavouriteStreamController::class, 'destroy'])->name('favourite.streams.destroy');
});

Route::prefix('admin')->group(function() {
    Route::get('/',[AdminLoginController::class, 'showLoginForm'])->name('admin.login');
    Route::post('login', [AdminLoginController::class, 'login'])->name('admin.login.submit');
    Route::post('logout', [AdminLoginController::class, 'logout'])->name('admin.logout');
});

Route::get('/profile', [ProfileController::class, 'index'])->name('profile');

Route::get('/jackpots-tracker', [JackpotTrackerController::class, 'index'])->name('jackpots-tracker');
Route::get('/lottery-tracker', [LotteryJackpotTrackerController::class, 'index'])->name('lottery-tracker');
Route::get('/lottery-tracker/{name}', [LotteryJackpotTrackerController::class, 'sortByName'])->name('lottery-name');

Route::get('/casinos', [ShowCasinoController::class, 'index'])->name('all-casinos');
Route::get('/casinos/{casino:slug}', [ShowCasinoController::class, 'show'])->name('casinos.show');

Route::get('search', [SearchController::class, 'search'])->name('search');

Route::prefix('contact')->group(function(){
    Route::get('/', [ContactController::class, 'index'])->name('contact');
    Route::post('submit', [ContactController::class, 'submitForm'])->name('submit-form');
});

// DASHBOARD START
Route::prefix('dashboard')->group(function(){
    Route::get('/', [PostController::class, 'index'])->name('dashboard');
    
    Route::resource('posts', PostController::class)->except([
        'index', 'show'
    ]);
    
    // Categories
    Route::resource('categories', CategoryController::class)->except([
        'edit', 'show', 'create'
    ]);

    // Streams    
    Route::resource('streams', StreamController::class)->except([
        'show'
    ]);
    
    // Casinos
    Route::resource('casinos', CasinoController::class)->except([
        'show'
    ]);

    // Slots
    Route::resource('slots', SlotController::class)->except([
        'edit', 'show'
    ]);
    Route::post('/slots/set-active/{slot}', [SlotController::class, 'setActive'])->name('slots.set-active');
    Route::post('/slots/{id}/{casinoid}', [SlotController::class, 'detach'])->name('slots.detach');

    //Jackpots
    Route::resource('jackpots', JackpotController::class)->except([
        'edit', 'show'
    ]);

    Route::post('upload', [CKEditorController::class, 'upload']);

    // approve comments
    Route::get('comments', [CommentController::class, 'index'])->name('dashboard.comments.index');
    Route::post('comments/{id}', [CommentController::class, 'approve'])->name('dashboard.comments.approve');
    Route::post('comments/destroy/{id}', [CommentController::class, 'destroy'])->name('dashboard.comments.destroy');

    // attachments
    Route::resource('attachments', AttachmentController::class)->only([
        'index', 'destroy'
    ]); 

    // users
    Route::resource('users', UserController::class)->only([
        'index', 'destroy'
    ]);
});
// DASHBOARD END

// LOGIN WITH GOOGLE FACEBOOK START
Route::prefix('login')->group(function(){
    Route::get('googleredirect', [LoginController::class, 'redirectToGoogleProvider'])->name('google.login');
    Route::get('googlecallback', [LoginController::class, 'handleGoogleProviderCallback']);

    Route::get('facebookredirect', [LoginController::class, 'redirectToFacebookProvider'])->name('facebook.login');
    Route::get('facebookcallback', [LoginController::class, 'handleFacebookProviderCallback']);
});
// LOGIN WITH GOOGLE FACEBOOK END

// TERMS

Route::get('/terms-and-conditions', [TermsAndConditionsController::class, 'index'])->name('terms');
Route::get('/about', [AboutController::class, 'index'])->name('about');

app/Http/Controllers/Dashboard/AttachmentController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Controllers\Dashboard\X;
use App\Attachment;
use App\Post;
use App\Category;
use App\Stream;
use App\Slot;
use App\Jackpot;
use App\Casino;
use Laravelista\Comments\Comment;

use App\Http\Traits\RemoveImage;

class AttachmentController extends Controller
{
    use RemoveImage;

    public function __construct()
    {
        $this->middleware('auth:admin');
        $this->per_page = 54;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $attachments = Attachment::orderBy('created_at', 'desc')->paginate($this->per_page);
        $total_posts = Post::all()->count();
        $total_streams = Stream::all()->count();
        $unapproved_comments = Comment::where('approved', false)->count();
        $total_categories = Category::all()->count();
        $total_slots = Slot::all()->count();
        $total_jackpots = Jackpot::all()->count();
        $total_casinos = Casino::all()->count();

        return view('dashboard.attachment', [
                'attachments' => $attachments,
                'total_categories' => $total_categories,
                'total_posts' => $total_posts,
                'total_streams' => $total_streams,
                'filemanager' => true,
                'unapproved_comments' => $unapproved_comments,
                'total_slots' => $total_slots,
                'total_jackpots' => $total_jackpots,
                'total_casinos' => $total_casinos,
            ]
        );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store($images_arr)
    {
        $attachment = new Attachment; 
        $attachment->image = $images_arr;
        $attachment->save();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Attachment  $attachment
     * @return \Illuminate\Http\Response
     */
    public function destroy(Attachment $attachment)
    {    
        $attachment_id = $attachment->id;

        $this->remove_image($attachment->image);

        Attachment::destroy($attachment->id);
        
        return redirect()->route('attachments.index')->with('success', "Attachment with id:{$attachment_id} removed!");
    }
}

app/Http/Controllers/Dashboard/CKEditorController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Storage;
use App\Http\Controllers\Dashboard\AttachmentController;

class CKEditorController extends Controller
{
    protected $images_arr_for_db;
    protected $attachment_controller;
    
    public function __construct(AttachmentController $attachment_controller)
    {
        $this->middleware('auth:admin');
        $this->images_arr_for_db = [];
        $this->attachment_controller = $attachment_controller;
    }

    public function upload(Request $request)
    {
        $this->validate($request, [
            'upload' => 'image|mimes:jpeg,jpg,png,gif,webp'
        ]);

        if ($request->hasFile('upload')) {

            $sub_folder_n = date('n-Y');
            $post_image = $request->file('upload');

            $images_arr = $this->save_post_content_images($post_image, $sub_folder_n);

        } else {
            return json_encode(
                [
                    'error' => [
                        'message' => 'There is no file to upload'
                    ],
                ]
            );
        }

        return json_encode(
            [
                'urls' => $images_arr
            ]
        );
    }

    private function save_post_content_images($image, string $folder)
    {
        $file = str_slug(pathinfo($image->getClientOriginalName())['filename'], '-');
        $folder1 = trim($folder);
        $file_path = "post-images/{$folder1}/";

        $lg_image_width;
        $md_image_width; 
        $sm_image_width;

        $img_lg = Image::make($image)->encode('webp', 40);
        
        $img_lg->resize(1600, null, function ($constraint) {
            $constraint->aspectRatio();
            $constraint->upsize();
        });
        
        $lg_image_width = $img_lg->width();

        if ( $lg_image_width <= 1600 && $lg_image_width > 836 ) {

            $lg_image_path = $file_path . "{$file}-{$lg_image_width}w-lg.webp";

            Storage::disk('s3')->put($lg_image_path, $img_lg->stream());
            Storage::disk('s3')->setVisibility($lg_image_path, 'public');
            
            $images_arr[$lg_image_width] = Storage::disk('s3')->url($lg_image_path);

        }

        $img_md = $img_lg->resize(836, null, function ($constraint) {
            $constraint->aspectRatio();
            $constraint->upsize();
        });
        $md_image_width = $img_md->width();

        if ( $md_image_width <= 836 && $md_image_width > 400 ) {

            $md_image_path = $file_path . "{$file}-{$md_image_width}w-md.webp";

            Storage::disk('s3')->put($md_image_path, $img_md->stream());
            Storage::disk('s3')->setVisibility($md_image_path, 'public');
            
            $images_arr[$md_image_width] = Storage::disk('s3')->url($md_image_path);

        }
            
        $img_sm = $img_md->resize(400, null, function ($constraint) {
            $constraint->aspectRatio();
            $constraint->upsize();
        });
        $sm_image_width = $img_sm->width();

        if ( $sm_image_width <= 400 ) {
 
            $sm_image_path = $file_path . "{$file}-{$sm_image_width}w-sm.webp";
            
            Storage::disk('s3')->put($sm_image_path, $img_sm->stream());
            Storage::disk('s3')->setVisibility($sm_image_path, 'public');

            $images_arr[$sm_image_width] = Storage::disk('s3')->url($sm_image_path);

        }
        
        $images_arr['default'] = isset($lg_image_path) ? Storage::disk('s3')->url($lg_image_path) : (isset($md_image_path) ? Storage::disk('s3')->url($md_image_path) : Storage::disk('s3')->url($sm_image_path));
        
        // prepare image array for storing in the database start

        $images = $images_arr;
        unset($images['default']);
        $images = array_values($images);
        $this->images_arr_for_db = $images;

        // prepare image array for storing in the database end
        
        // store image array in data base
        $this->add_images_to_db();
        
        $img_lg = null;

        return $images_arr;
    }

    public function add_images_to_db()
    {
        if ( !empty($this->images_arr_for_db) ) {
            $this->attachment_controller->store($this->images_arr_for_db);
        }
    } 
}
 

app/Http/Controllers/Dashboard/CommentController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Config;
use DB;
use Illuminate\Http\Request;

use App\User;
use App\Post;
use App\Category;
use App\Stream;
use App\Slot;
use App\Jackpot;
use App\Casino;
use Laravelista\Comments\Comment;

class CommentController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
        $this->per_page = 20;
    }

    public function index()
    {  
        $comments = DB::table('comments')
            ->leftJoin('users', 'users.id', '=', 'comments.commenter_id')
            ->select(['comments.commenter_id', 'comments.comment', 'comments.approved', 'comments.commenter_type', 'comments.created_at', 'comments.id', 'comments.guest_name', 'users.name'])
            ->orderBy('comments.approved', 'asc')->orderBy('comments.created_at', 'desc')
            ->paginate($this->per_page);

        $categories = Category::orderBy('name', 'asc')->get();
        $total_categories = Category::all()->count();
        $total_posts = Post::all()->count();
        $total_streams = Stream::all()->count();
        $unapproved_comments = Comment::where('approved', false)->count();
        $total_slots = Slot::all()->count();
        $total_jackpots = Jackpot::all()->count();
        $total_casinos = Casino::all()->count();

        return view('dashboard.comments', [
                'categories' => $categories,
                'total_categories' => $total_categories,
                'total_posts' => $total_posts,
                'total_streams' => $total_streams,
                'comments' => $comments,
                'unapproved_comments' => $unapproved_comments,
                'total_slots' => $total_slots,
                'total_jackpots' => $total_jackpots,
                'total_casinos' => $total_casinos,
            ]
        );
    }

    public function approve($id)
    {
        $comment = Comment::find($id);
        $comment->approved = true;
        $comment->save();
        return redirect()->back()->with('success', 'Comment was approved');
    }

    public function destroy($id)
    {
        $comment = Comment::find($id);
        
        if (Config::get('comments.soft_deletes') == true) {
			$comment->delete();
		}
		else {
			$comment->forceDelete();
        }
        
        return redirect()->back()->with('success', 'Comment was removed');
    }
}

resources/views/dashboard/attachment.blade.php
@extends('layouts.wide')

@section('title', 'Manage Attachments')

@push('header_styles_after_main')
    <link rel="stylesheet" href="{{ mix('css/dashboard.css') }}" />   
@endpush

@section('content') 
    <div class="column col-12">
        @include('inc.errors')
    </div>
    
    @forelse($attachments as $attachment)
        @php
            $src = $attachment->image['2'] ?? $attachment->image['1'] ?? $attachment->image['0'];
            $parsed_url = parse_url($src);
            $pieces = explode("/", $parsed_url['path']);
            $date = isset($pieces[2]) ? str_replace('-', '/', $pieces[2]) : '';
        @endphp
        <div class="column col-sm-6 col-md-4 col-lg-3 col-2 attachment">
            <img src="{{ $src }}" alt="attachment">
            <div class="attachment__info mt-2 p-2">
                <button class="btn btn-sm btn-action btn-error remove_attachment_btn">
                    <svg class="icon">
                        <use xlink:href="{{URL::asset('assets')}}/symbol-defs.svg#trash"></use>
                    </svg> 
                </button>
                <span>
                    <small>{{ $date }}</small>
                </span>
            </div>
            
            <div class="modal modal-sm remove_attachment_modal">
                <a href="#close" class="modal-overlay" aria-label="Close"></a>
                <div class="modal-container">
                    <div class="modal-header">
                        <a href="#close" class="btn btn-clear float-right" aria-label="Close"></a>
                        <div class="modal-title h5">Remove attachment with id:{{ $attachment->id }}</div>
                    </div>
                    <div class="modal-body">
                        <div class="content">
                            <form action="{{ route('attachments.destroy', $attachment->id) }}" method="POST"> 
                                @method('DELETE')
                                <div class="form-group text-center">
                                    <button class="btn btn-action">{{ __('Yes') }}</button>
                                    <a href="#close" class="btn btn-action">{{ __('No') }}</a>
                                </div>
                                @csrf
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @empty
       <div class="column col-12">
            <h3 class="text-center">No attachments</h3>
        </div>
    @endforelse 

@endsection

@section('sidebar')
    <header class="column col-12">
        <h1 class="text-right dasboard_new_post_heading">Manage Attachments</h1>
    </header>    
    @includeWhen($filemanager, 'dashboard.inc.wide_sidebar_menu')
@endsection

@section('pagination')

    @if(count($attachments) > 0)
        <section class="container grid-lg pag_cnt">
            <div class="columns">
                <div class="column col-md-12 col-8 col-mx-auto">
                    {{ $attachments->links() }}
                </div>
            </div>
        </section>
    @endif

@endsection

@section('footer')
    @include('inc.footer.footer')
@endsection

@push('footer_scripts')
    <script type="text/javascript" src="{{ mix('js/dashboard/main.js') }}"></script>
@endpush

resources/views/dashboard/category.blade.php
@extends('layouts.main_dashboard')

@section('title', 'Manage Categories')

@push('header_styles_after_main')
    <link rel="stylesheet" href="{{ mix('css/dashboard.css') }}" />   
@endpush

@section('content')
    
    <section class="column col-8 col-md-12 edit_categories">
        <header>
            <h1 class="text-right dasboard_new_post_heading">Manage Categories</h1>
        </header>
        @include('inc.errors')
        @forelse($categories as $key => $category) 
            <div class="tile">
                <div class="tile-content">
                    <p class="tile-title">
                        {{ ucfirst($category->name) }} 
                        <small class="category_type">
                            <i>{{ $category->type }} category</i>
                        </small>
                    </p>
                </div>
                <div class="tile-action edit_category_btns">
                    <button class="btn btn-sm btn-action tooltip tooltip-left modal_trigger" data-tooltip="Edit Category">
                        <svg class="icon">
                            <use xlink:href="{{URL::asset('assets')}}/symbol-defs.svg#edit"></use>
                        </svg> 
                    </button>
                    <button href="#" class="btn btn-sm btn-action btn-error tooltip tooltip-left delete_category_btn" data-tooltip="Delete Category">
                        <svg class="icon">
                            <use xlink:href="{{URL::asset('assets')}}/symbol-defs.svg#trash"></use>
                        </svg> 
                    </button>
                    <div class="modal modal-sm update_category_modal">
                        <a href="#close" class="modal-overlay" aria-label="Close"></a>
                        <div class="modal-container">
                            <div class="modal-header">
                                <a href="#close" class="btn btn-clear float-right" aria-label="Close"></a>
                                <div class="modal-title h5">Update {{ ucfirst($category->name) }}</div>
                            </div>
                            <div class="modal-body">
                                <div class="content">
                                    <form action="{{ route('categories.update', $category->id) }}" method="POST"> 
                                        @method('PUT')
                                        <div class="form-group">
                                            <div class="input-group">
                                                <span class="form-inline pr-2">For: </span>
                                                <label class="form-radio form-inline">
                                                    <input type="radio" name="type" value="posts" {{ ($category->type === 'posts') ? 'checked' : '' }}><i class="form-icon"></i> Posts
                                                </label>
                                                <label class="form-radio form-inline">
                                                    <input type="radio" name="type" value="streams" {{ ($category->type === 'streams') ? 'checked' : '' }}><i class="form-icon"></i> Streams
                                                </label>
                                            </div>
                                            <div class="input-group">
                                                <input class="form-input" type="text" name="name" value="{{ $category->name }}">
                                                <button class="btn">Update</button>
                                            </div>
                                        </div>
                                        @csrf
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal modal-sm confirm_category_delete_modal">
                        <a href="#close" class="modal-overlay" aria-label="Close"></a>
                        <div class="modal-container">
                            <div class="modal-header">
                                <a href="#close" class="btn btn-clear float-right" aria-label="Close"></a>
                                <div class="modal-title h5">Remove {{ ucfirst($category->name) }} Category?</div>
                            </div>
                            <div class="modal-body">
                                <div class="content">
                                    <form action="{{ route('categories.destroy', $category->id) }}" method="POST"> 
                                        @method('DELETE')
                                        <div class="form-group text-center">
                                            <button class="btn btn-action">{{ __('Yes') }}</button>
                                            <a href="#close" class="btn btn-action">{{ __('No') }}</a>
                                        </div>
                                        @csrf
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @empty
            <h3 class="posts_cnt__item text-center">No categories</h3> 
        @endforelse
        <div class="add_category_cnt my-2 py-2">
            <button class="btn add_category_cnt__btn">
                <svg class="icon">
                    <use xlink:href="{{URL::asset('assets')}}/symbol-defs.svg#plus"></use>
                </svg> 
                Add Category
            </button>
            <div class="modal modal-sm create_category_modal">
                <a href="#close" class="modal-overlay" aria-label="Close"></a>
                <div class="modal-container">
                    <div class="modal-header">
                        <a href="#close" class="btn btn-clear float-right" aria-label="Close"></a>
                        <div class="modal-title h5">{{ __('Create Category') }}</div>
                    </div>
                    <div class="modal-body">
                        <div class="content">
                            <form action="{{ route('categories.store') }}" method="POST"> 
                                <div class="form-group">
                                    <div class="input-group">
                                        <span class="form-inline pr-2">For: </span>
                                        <label class="form-radio form-inline">
                                            <input type="radio" name="type" value="posts" checked=""><i class="form-icon"></i> Posts
                                        </label>
                                        <label class="form-radio form-inline">
                                            <input type="radio" name="type" value="streams"><i class="form-icon"></i> Streams
                                        </label>
                                    </div>
                                    <div class="input-group">
                                        <input class="form-input" type="text" name="name" placeholder="{{ __('Category Name') }}">
                                        <button class="btn">Create</button>
                                    </div>
                                </div>
                                @csrf
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@section('sidebar')
    @include('dashboard.inc.sidebar_menu')
@endsection

@section('footer')
    @include('inc.footer.footer')
@endsection

@push('footer_scripts')
    <script type="text/javascript" src="{{ mix('js/dashboard/main.js') }}"></script>
@endpush

resources/views/dashboard/comments.blade.php
@extends('layouts.main_dashboard')

@section('title', 'Manage Comments')

@push('header_styles_after_main')
    <link rel="stylesheet" href="{{ mix('css/dashboard.css') }}" />   
@endpush

@section('content')
    
    <section class="column col-8 col-md-12 edit_comments">
        <header>
            <h1 class="text-right dasboard_new_post_heading">Manage Comments</h1>
        </header>

        @include('inc.errors')
        
        @forelse($comments as $key => $comment) 
            <div class="comment">
                <p>
                    <small class="author_name @if($comment->commenter_type === 'App\Admin') text-bold text-primary @endif">
                        <i> @if($comment->commenter_type === 'App\Admin') Admin @endif {{ $comment->name ?? $comment->guest_name }} </i>
                    </small><br>
                    <small>
                        {{ $comment->comment }}
                    </small>
                </p>
                <div class="comment__controlls">
                    @if (!$comment->approved)
                        <form method="POST" action="{{ route('dashboard.comments.approve', $comment->id) }}">
                            @csrf
                            <button class="btn btn-sm tooltip tooltip-left" data-tooltip="Approve Comment">Approve</button>  
                        </form>  
                    @endif
                    <form method="POST" action="{{ route('dashboard.comments.destroy', $comment->id) }}">
                        @csrf
                        <button class="btn btn-sm btn-action btn-error tooltip tooltip-left delete_comment_btn" data-tooltip="Delete Comment">
                            <svg class="icon">
                                <use xlink:href="{{URL::asset('assets')}}/symbol-defs.svg#trash"></use>
                            </svg> 
                        </button>  
                    </form>  
                </div>
            </div>
        @empty
            <h3 class="posts_cnt__item text-center">No comments</h3> 
        @endforelse
        
    </section>
@endsection

@section('pagination')

    @if(count($comments) > 0)
        <section class="container grid-lg pag_cnt">
            <div class="columns">
                <div class="column col-md-12 col-8 col-ml-auto">
                    {{ $comments->links() }}
                </div>
            </div>
        </section>
    @endif

@endsection

@section('sidebar')
    @include('dashboard.inc.sidebar_menu')
@endsection

@section('footer')
    @include('inc.footer.footer')
@endsection

@push('footer_scripts')
    <script type="text/javascript" src="{{ mix('js/dashboard/main.js') }}"></script>
@endpush