routes/web.php
<?php

use App\Http\Controllers\ShowPostController;
use App\Http\Controllers\ShowStreamController;
use App\Http\Controllers\ShowCasinoController;
use App\Http\Controllers\FavouritePostController;
use App\Http\Controllers\FavouriteStreamController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\JackpotTrackerController;
use App\Http\Controllers\LotteryJackpotTrackerController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\TermsAndConditionsController;

use App\Http\Controllers\Dashboard\PostController;
use App\Http\Controllers\Dashboard\CategoryController;
use App\Http\Controllers\Dashboard\StreamController;
use App\Http\Controllers\Dashboard\CasinoController;
use App\Http\Controllers\Dashboard\SlotController;
use App\Http\Controllers\Dashboard\JackpotController;
use App\Http\Controllers\Dashboard\CKEditorController;
use App\Http\Controllers\Dashboard\CommentController;
use App\Http\Controllers\Dashboard\AttachmentController;
use App\Http\Controllers\Dashboard\UserController;

use App\Http\Controllers\Auth\AdminLoginController;
use App\Http\Controllers\Auth\LoginController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['verify' => true]);

Route::get('/', [ShowPostController::class, 'index'])->name('home');

// SHOW SINGLE POST
Route::get('post/{slug}', [ShowPostController::class, 'show'])->name('posts.show');

Route::get('streams', [ShowStreamController::class, 'index'])->name('all-streams');
// SHOW SINGLE STREAM
Route::get('stream/{slug}', [ShowStreamController::class, 'show'])->name('streams.show');

// SORTING ROUTS
Route::get('/sortby/{type}/{ascendance}', [ShowPostController::class, 'sortby'])->where(['type' => '[a-z]+', 'ascendance' => '[a-z]+'])->name('posts.sortby');
Route::get('posts/category/{slug}', [ShowPostController::class, 'category'])->name('posts.category');
Route::get('posts/category/{slug}/sortby/{type}/{ascendance}', [ShowPostController::class, 'category_sortby'])->where(['type' => '[a-z]+', 'ascendance' => '[a-z]+'])->name('posts.category.sortby');
Route::get('streams/category/{slug}', [ShowStreamController::class, 'category'])->name('streams.category');

Route::middleware(['verified'])->prefix('favourite')->group(function() {
    Route::get('posts', [FavouritePostController::class, 'index'])->name('favourite.posts.index');
    Route::get('streams', [FavouriteStreamController::class, 'index'])->name('favourite.streams.index');
    Route::post('/save/post/{postid}', [FavouritePostController::class, 'store'])->name('favourite.posts.store');
    Route::post('/save/stream/{postid}', [FavouriteStreamController::class, 'store'])->name('favourite.streams.store');
    Route::post('/destroy/post/{postid}', [FavouritePostController::class, 'destroy'])->name('favourite.posts.destroy');
    Route::post('/destroy/stream/{postid}', [FavouriteStreamController::class, 'destroy'])->name('favourite.streams.destroy');
});

Route::prefix('admin')->group(function() {
    Route::get('/',[AdminLoginController::class, 'showLoginForm'])->name('admin.login');
    Route::post('login', [AdminLoginController::class, 'login'])->name('admin.login.submit');
    Route::post('logout', [AdminLoginController::class, 'logout'])->name('admin.logout');
});

Route::get('/profile', [ProfileController::class, 'index'])->name('profile');

Route::get('/jackpots-tracker', [JackpotTrackerController::class, 'index'])->name('jackpots-tracker');
Route::get('/lottery-tracker', [LotteryJackpotTrackerController::class, 'index'])->name('lottery-tracker');
Route::get('/lottery-tracker/{name}', [LotteryJackpotTrackerController::class, 'sortByName'])->name('lottery-name');

Route::get('/casinos', [ShowCasinoController::class, 'index'])->name('all-casinos');
Route::get('/casinos/{casino:slug}', [ShowCasinoController::class, 'show'])->name('casinos.show');

Route::get('search', [SearchController::class, 'search'])->name('search');

Route::prefix('contact')->group(function(){
    Route::get('/', [ContactController::class, 'index'])->name('contact');
    Route::post('submit', [ContactController::class, 'submitForm'])->name('submit-form');
});

// DASHBOARD START
Route::prefix('dashboard')->group(function(){
    Route::get('/', [PostController::class, 'index'])->name('dashboard');
    
    Route::resource('posts', PostController::class)->except([
        'index', 'show'
    ]);
    
    // Categories
    Route::resource('categories', CategoryController::class)->except([
        'edit', 'show', 'create'
    ]);

    // Streams    
    Route::resource('streams', StreamController::class)->except([
        'show'
    ]);
    
    // Casinos
    Route::resource('casinos', CasinoController::class)->except([
        'show'
    ]);

    // Slots
    Route::resource('slots', SlotController::class)->except([
        'edit', 'show'
    ]);
    Route::post('/slots/set-active/{slot}', [SlotController::class, 'setActive'])->name('slots.set-active');
    Route::post('/slots/{id}/{casinoid}', [SlotController::class, 'detach'])->name('slots.detach');

    //Jackpots
    Route::resource('jackpots', JackpotController::class)->except([
        'edit', 'show'
    ]);

    Route::post('upload', [CKEditorController::class, 'upload']);

    // approve comments
    Route::get('comments', [CommentController::class, 'index'])->name('dashboard.comments.index');
    Route::post('comments/{id}', [CommentController::class, 'approve'])->name('dashboard.comments.approve');
    Route::post('comments/destroy/{id}', [CommentController::class, 'destroy'])->name('dashboard.comments.destroy');

    // attachments
    Route::resource('attachments', AttachmentController::class)->only([
        'index', 'destroy'
    ]); 

    // users
    Route::resource('users', UserController::class)->only([
        'index', 'destroy'
    ]);
});
// DASHBOARD END

// LOGIN WITH GOOGLE FACEBOOK START
Route::prefix('login')->group(function(){
    Route::get('googleredirect', [LoginController::class, 'redirectToGoogleProvider'])->name('google.login');
    Route::get('googlecallback', [LoginController::class, 'handleGoogleProviderCallback']);

    Route::get('facebookredirect', [LoginController::class, 'redirectToFacebookProvider'])->name('facebook.login');
    Route::get('facebookcallback', [LoginController::class, 'handleFacebookProviderCallback']);
});
// LOGIN WITH GOOGLE FACEBOOK END

// TERMS

Route::get('/terms-and-conditions', [TermsAndConditionsController::class, 'index'])->name('terms');
Route::get('/about', [AboutController::class, 'index'])->name('about');

app/Stream.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;

class Stream extends Model
{
    // use Searchable;

    public function author()
    {
        return $this->belongsTo('App\Admin');
    }
    
    public function categories()
    {
        return $this->belongsToMany('App\Category');
    }

    public function liked_by()
    {
        return $this->belongsToMany('App\User');
    }

    public function get_categories($id)
    {
        $categories = Stream::find($id)->categories()->orderBy('name')->get();
        
        if($categories->isEmpty()){
            return false;
        }

        foreach($categories as $category){
            $category_link = sprintf( 
                '<a href="%1$s" title="%2$s" class="categories__link">%3$s</a>',
                sprintf( '%s', route( 'streams.category', $category->slug ) ),
                sprintf( __( 'View all articles in %s'), $category->name ),
                $category->name
            );
            $category_names_arr[] = $category_link;
        }
        
        $categories_string = implode(', ', $category_names_arr);

        return $categories_string;
    }

    // public function toSearchableArray()
    // {

    //     $array['channel_name'] = $this->channel_name;
    //     $array['description'] = $this->description;
    //     $array['created_at'] = $this->created_at;

    //     return $array;
    // }
}

app/Http/Controllers/Dashboard/AttachmentController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Controllers\Dashboard\X;
use App\Attachment;
use App\Post;
use App\Category;
use App\Stream;
use App\Slot;
use App\Jackpot;
use App\Casino;
use Laravelista\Comments\Comment;

use App\Http\Traits\RemoveImage;

class AttachmentController extends Controller
{
    use RemoveImage;

    public function __construct()
    {
        $this->middleware('auth:admin');
        $this->per_page = 54;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $attachments = Attachment::orderBy('created_at', 'desc')->paginate($this->per_page);
        $total_posts = Post::all()->count();
        $total_streams = Stream::all()->count();
        $unapproved_comments = Comment::where('approved', false)->count();
        $total_categories = Category::all()->count();
        $total_slots = Slot::all()->count();
        $total_jackpots = Jackpot::all()->count();
        $total_casinos = Casino::all()->count();

        return view('dashboard.attachment', [
                'attachments' => $attachments,
                'total_categories' => $total_categories,
                'total_posts' => $total_posts,
                'total_streams' => $total_streams,
                'filemanager' => true,
                'unapproved_comments' => $unapproved_comments,
                'total_slots' => $total_slots,
                'total_jackpots' => $total_jackpots,
                'total_casinos' => $total_casinos,
            ]
        );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store($images_arr)
    {
        $attachment = new Attachment; 
        $attachment->image = $images_arr;
        $attachment->save();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Attachment  $attachment
     * @return \Illuminate\Http\Response
     */
    public function destroy(Attachment $attachment)
    {    
        $attachment_id = $attachment->id;

        $this->remove_image($attachment->image);

        Attachment::destroy($attachment->id);
        
        return redirect()->route('attachments.index')->with('success', "Attachment with id:{$attachment_id} removed!");
    }
}

app/Http/Controllers/Dashboard/CKEditorController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Storage;
use App\Http\Controllers\Dashboard\AttachmentController;

class CKEditorController extends Controller
{
    protected $images_arr_for_db;
    protected $attachment_controller;
    
    public function __construct(AttachmentController $attachment_controller)
    {
        $this->middleware('auth:admin');
        $this->images_arr_for_db = [];
        $this->attachment_controller = $attachment_controller;
    }

    public function upload(Request $request)
    {
        $this->validate($request, [
            'upload' => 'image|mimes:jpeg,jpg,png,gif,webp'
        ]);

        if ($request->hasFile('upload')) {

            $sub_folder_n = date('n-Y');
            $post_image = $request->file('upload');

            $images_arr = $this->save_post_content_images($post_image, $sub_folder_n);

        } else {
            return json_encode(
                [
                    'error' => [
                        'message' => 'There is no file to upload'
                    ],
                ]
            );
        }

        return json_encode(
            [
                'urls' => $images_arr
            ]
        );
    }

    private function save_post_content_images($image, string $folder)
    {
        $file = str_slug(pathinfo($image->getClientOriginalName())['filename'], '-');
        $folder1 = trim($folder);
        $file_path = "post-images/{$folder1}/";

        $lg_image_width;
        $md_image_width; 
        $sm_image_width;

        $img_lg = Image::make($image)->encode('webp', 40);
        
        $img_lg->resize(1600, null, function ($constraint) {
            $constraint->aspectRatio();
            $constraint->upsize();
        });
        
        $lg_image_width = $img_lg->width();

        if ( $lg_image_width <= 1600 && $lg_image_width > 836 ) {

            $lg_image_path = $file_path . "{$file}-{$lg_image_width}w-lg.webp";

            Storage::disk('s3')->put($lg_image_path, $img_lg->stream());
            Storage::disk('s3')->setVisibility($lg_image_path, 'public');
            
            $images_arr[$lg_image_width] = Storage::disk('s3')->url($lg_image_path);

        }

        $img_md = $img_lg->resize(836, null, function ($constraint) {
            $constraint->aspectRatio();
            $constraint->upsize();
        });
        $md_image_width = $img_md->width();

        if ( $md_image_width <= 836 && $md_image_width > 400 ) {

            $md_image_path = $file_path . "{$file}-{$md_image_width}w-md.webp";

            Storage::disk('s3')->put($md_image_path, $img_md->stream());
            Storage::disk('s3')->setVisibility($md_image_path, 'public');
            
            $images_arr[$md_image_width] = Storage::disk('s3')->url($md_image_path);

        }
            
        $img_sm = $img_md->resize(400, null, function ($constraint) {
            $constraint->aspectRatio();
            $constraint->upsize();
        });
        $sm_image_width = $img_sm->width();

        if ( $sm_image_width <= 400 ) {
 
            $sm_image_path = $file_path . "{$file}-{$sm_image_width}w-sm.webp";
            
            Storage::disk('s3')->put($sm_image_path, $img_sm->stream());
            Storage::disk('s3')->setVisibility($sm_image_path, 'public');

            $images_arr[$sm_image_width] = Storage::disk('s3')->url($sm_image_path);

        }
        
        $images_arr['default'] = isset($lg_image_path) ? Storage::disk('s3')->url($lg_image_path) : (isset($md_image_path) ? Storage::disk('s3')->url($md_image_path) : Storage::disk('s3')->url($sm_image_path));
        
        // prepare image array for storing in the database start

        $images = $images_arr;
        unset($images['default']);
        $images = array_values($images);
        $this->images_arr_for_db = $images;

        // prepare image array for storing in the database end
        
        // store image array in data base
        $this->add_images_to_db();
        
        $img_lg = null;

        return $images_arr;
    }

    public function add_images_to_db()
    {
        if ( !empty($this->images_arr_for_db) ) {
            $this->attachment_controller->store($this->images_arr_for_db);
        }
    } 
}
 

app/Http/Controllers/Dashboard/CommentController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Config;
use DB;
use Illuminate\Http\Request;

use App\User;
use App\Post;
use App\Category;
use App\Stream;
use App\Slot;
use App\Jackpot;
use App\Casino;
use Laravelista\Comments\Comment;

class CommentController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
        $this->per_page = 20;
    }

    public function index()
    {  
        $comments = DB::table('comments')
            ->leftJoin('users', 'users.id', '=', 'comments.commenter_id')
            ->select(['comments.commenter_id', 'comments.comment', 'comments.approved', 'comments.commenter_type', 'comments.created_at', 'comments.id', 'comments.guest_name', 'users.name'])
            ->orderBy('comments.approved', 'asc')->orderBy('comments.created_at', 'desc')
            ->paginate($this->per_page);

        $categories = Category::orderBy('name', 'asc')->get();
        $total_categories = Category::all()->count();
        $total_posts = Post::all()->count();
        $total_streams = Stream::all()->count();
        $unapproved_comments = Comment::where('approved', false)->count();
        $total_slots = Slot::all()->count();
        $total_jackpots = Jackpot::all()->count();
        $total_casinos = Casino::all()->count();

        return view('dashboard.comments', [
                'categories' => $categories,
                'total_categories' => $total_categories,
                'total_posts' => $total_posts,
                'total_streams' => $total_streams,
                'comments' => $comments,
                'unapproved_comments' => $unapproved_comments,
                'total_slots' => $total_slots,
                'total_jackpots' => $total_jackpots,
                'total_casinos' => $total_casinos,
            ]
        );
    }

    public function approve($id)
    {
        $comment = Comment::find($id);
        $comment->approved = true;
        $comment->save();
        return redirect()->back()->with('success', 'Comment was approved');
    }

    public function destroy($id)
    {
        $comment = Comment::find($id);
        
        if (Config::get('comments.soft_deletes') == true) {
			$comment->delete();
		}
		else {
			$comment->forceDelete();
        }
        
        return redirect()->back()->with('success', 'Comment was removed');
    }
}

resources/views/dashboard/stream/create.blade.php
@extends('layouts.main_dashboard')

@section('title', 'Add New Stream')

@push('header_styles_after_main')
    <link rel="stylesheet" href="{{ mix('css/dashboard.css') }}" />   
@endpush

@section('content') 
    
    <section class="column col-8 col-md-12 col-mx-auto add_post_form">
        <header>
            <h1 class="text-right dasboard_new_post_heading">Add New Stream</h1>
        </header>
        <div class="text-right">
            <a href="{{ url()->previous() }}" class="btn btn-primary mb-2 {{ url()->previous() == url()->current() ? 'disabled' : '' }}">
                <svg class="icon">
                    <use xlink:href="{{URL::asset('assets')}}/symbol-defs.svg#back"></use>
                </svg> 
                Back
            </a>
        </div>

        @include('inc.errors')
        
        <div class="form-group">
            <form action="{{ route('streams.store') }}" method="POST">
                @if( !empty($categories) )
                    <div class="form-label">Categories</div>
                    <div class="form-group">
                        @foreach($categories as $key => $category)
                            @php
                                $category_checkbox_values = old("category") ?? '';
                                if(!empty($category_checkbox_values)){
                                    $found_key = array_search($category->id, $category_checkbox_values); 
                                    $checked = $found_key !== false ? $category_checkbox_values[$found_key] : false;
                                }
                            @endphp
                            @if (!empty($category_checkbox_values))
                                @if($category->id == $checked)
                                    <label class="form-checkbox form-inline">
                                        <input type="checkbox" name="category[]" value="{{ $category->id }}" checked>
                                        <i class="form-icon"></i> {{ $category->name }}
                                    </label>
                                @else
                                    <label class="form-checkbox form-inline">
                                        <input type="checkbox" name="category[]" value="{{  $category->id }}">
                                        <i class="form-icon"></i> {{ $category->name }}
                                    </label> 
                                @endif
                            @else
                                @if($key === 0)
                                    <label class="form-checkbox form-inline">
                                        <input type="checkbox" name="category[]" value="{{ $category->id }}" checked>
                                        <i class="form-icon"></i> {{ $category->name }}
                                    </label>
                                @else
                                    <label class="form-checkbox form-inline">
                                        <input type="checkbox" name="category[]" value="{{ $category->id }}">
                                        <i class="form-icon"></i> {{ $category->name }}
                                    </label>
                                @endif
                            @endif
                        @endforeach
                    </div>
                @endif
                <div class="form-group">
                    <label class="form-label" for="channel_name">Channel Name</label>
                    <input class="form-input" type="text" id="channel_name" name="channel_name" value="{{ old('channel_name') ?? '' }}" placeholder="Channel Name">
                </div>
                <div class="form-group">
                    <label class="form-label" for="channel_id">Channel Id</label>
                    <input class="form-input" id="channel_id" name="channel_id" placeholder="Channel Id" type="number" max="999999999" value="{{ old('channel_id') ?? '' }}">
                </div>
                <div class="form-group">
                    <label class="form-label" for="description">Channel Description</label>
                    <textarea class="form-input" id="description" name="description" rows="5">
                        {{ old('description') ?? '' }}
                    </textarea>
                </div>
                @csrf
                <div class="form-group text-center my-2 py-2">
                    <input type="submit" value="Create" class="btn btn-lg">
                </div>
            </form>
        </div>
    </section> 
@endsection

@section('sidebar')
    @include('dashboard.inc.sidebar_menu')
@endsection

@section('footer')
    @include('inc.footer.footer')
@endsection

@push('footer_scripts')
    <script type="text/javascript" src="{{ mix('js/dashboard/main.js') }}"></script>
@endpush

resources/views/dashboard/stream/edit.blade.php
@extends('layouts.main_dashboard')

@section('title', 'Edit Stream')

@push('header_styles_after_main')
    <link rel="stylesheet" href="{{ mix('css/dashboard.css') }}" />   
@endpush

@section('content') 
    
    <section class="column col-8 col-md-12 col-mx-auto add_post_form">
        <header>
            <h1 class="text-right dasboard_new_post_heading">Edit Stream</h1>
        </header>
        <div class="text-right">
            <a href="{{ url()->previous() }}" class="btn btn-primary mb-2 {{ url()->previous() == url()->current() ? 'disabled' : '' }}">
                <svg class="icon">
                    <use xlink:href="{{URL::asset('assets')}}/symbol-defs.svg#back"></use>
                </svg> 
                Back
            </a>
        </div>
        
        @include('inc.errors')
        
        <div class="form-group">
            <form action="{{ route('streams.update', $stream->id) }}" method="POST">
                @method('PUT')
                @if( !empty($categories) )
                    <div class="form-label">Categories</div>
                    <div class="form-group">
                        
                        @foreach($categories as $category)
                            @php
                                $key = array_search($category->id, $current_post_categories); 
                                $checked = $key !== false ? $current_post_categories[$key] : false;
                            @endphp

                            @if($category->id == $checked)
                                <label class="form-checkbox form-inline">
                                    <input type="checkbox" name="category[]" value="{{ $category->id }}" checked>
                                    <i class="form-icon"></i> {{ $category->name }}
                                </label>
                            @else
                                <label class="form-checkbox form-inline">
                                    <input type="checkbox" name="category[]" value="{{  $category->id }}">
                                    <i class="form-icon"></i> {{ $category->name }}
                                </label> 
                            @endif   
                                    
                        @endforeach
                    </div>
                @endif
                <div class="form-group">
                    <label class="form-label" for="channel_name">Channel name</label>
                    <input class="form-input" type="text" id="channel_name" name="channel_name" value="{{ old("channel_name") ? old("channel_name") : $stream->channel_name }}" placeholder="Channel name">
                </div>
                <div class="form-group">
                    <label class="form-label" for="channel_id">Channel Id</label>
                    <input class="form-input" id="channel_id" name="channel_id" placeholder="Channel Id" type="number" max="999999999" value="{{  old("channel_id") ? old("channel_id") : $stream->channel_id }}">
                </div>
                <div class="form-group">
                    <label class="form-label" for="description">Channel Description</label>
                    <textarea class="form-input" id="description" name="description" rows="5">
                        {{ old('description') ? old('description') : $stream->description }}
                    </textarea>
                </div>
                @csrf
                <div class="form-group text-center my-2 py-2">
                    <input type="submit" value="Updete" class="btn btn-lg">
                </div>
            </form>
        </div>
    </section> 
@endsection

@section('sidebar')
    @include('dashboard.inc.sidebar_menu')
@endsection

@section('footer')
    @include('inc.footer.footer')
@endsection

@push('footer_scripts')
    <script type="text/javascript" src="{{ mix('js/dashboard/main.js') }}"></script>
@endpush

resources/views/dashboard/stream/index.blade.php
@extends('layouts.main_dashboard')

@section('title', 'Manage Streams')

@push('header_styles_after_main')
    <link rel="stylesheet" href="{{ mix('css/dashboard.css') }}" />   
@endpush

@section('content') 
    
    <section class="column col-8 col-md-12 col-mx-auto manage_posts">
        <header>
            <h1 class="text-right dasboard_new_post_heading">Manage Streams</h1>
        </header>
        <div class="card">
            <div class="card-header">
                <div class="card-title h4">Create Stream</div>
            </div>
            <div class="card-footer">
                <a href="{{ route('streams.create') }}" class="btn btn-lg btn-primary">
                    <svg class="icon">
                        <use xlink:href="{{URL::asset('assets')}}/symbol-defs.svg#plus"></use>
                    </svg> 
                    Create New
                </a>
            </div>
        </div>
        <div class="edit_posts mt">
            
            @include('inc.errors')

            @forelse($streams as $stream)
                <div class="edit_posts__post">
                    <h4>{{ $stream->channel_name }}</h4>
                    <div class="edit_post_btns">
                        <a href="{{ route('streams.edit', $stream->id) }}" class="btn btn-action tooltip tooltip-left" data-tooltip="Edit Stream">
                            <svg class="icon">
                                <use xlink:href="{{URL::asset('assets')}}/symbol-defs.svg#edit"></use>
                            </svg> 
                        </a>
                        <a href="#" class="btn btn-error btn-action tooltip tooltip-left delete_stream_btn" data-tooltip="Delete Stream">
                            <svg class="icon">
                                <use xlink:href="{{URL::asset('assets')}}/symbol-defs.svg#trash"></use>
                            </svg> 
                        </a>
                        <div class="modal modal-sm confirm_stream_delete_modal">
                            <a href="#close" class="modal-overlay" aria-label="Close"></a>
                            <div class="modal-container">
                                <div class="modal-header">
                                    <a href="#close" class="btn btn-clear float-right" aria-label="Close"></a>
                                    <div class="modal-title h5">Remove {{ ucfirst($stream->channel_name) }}?</div>
                                </div>
                                <div class="modal-body">
                                    <div class="content">
                                        <form action="{{ route('streams.destroy', $stream->id) }}" method="POST"> 
                                            @method('DELETE')
                                            <div class="form-group text-center">
                                                <button class="btn btn-action">{{ __('Yes') }}</button>
                                                <a href="#close" class="btn btn-action">{{ __('No') }}</a>
                                            </div>
                                            @csrf
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>  
                </div>
            @empty
                <h3 class="posts_cnt__item text-center">No streams</h3> 
            @endforelse
        </div>
    </section>

@endsection

@section('sidebar')
    @include('dashboard.inc.sidebar_menu')
@endsection

@section('pagination')
    <section class="container grid-lg pag_cnt">
        <div class="columns">
            <div class="column col-md-12 col-8 col-ml-auto">
                {{ $streams->links() }}
            </div>
        </div>
    </section>
@endsection

@section('footer')
    @include('inc.footer.footer')
@endsection

@push('footer_scripts')
    <script type="text/javascript" src="{{ mix('js/dashboard/main.js') }}"></script>
@endpush