routes/web.php
<?php

use App\Http\Controllers\ShowPostController;
use App\Http\Controllers\ShowStreamController;
use App\Http\Controllers\ShowCasinoController;
use App\Http\Controllers\FavouritePostController;
use App\Http\Controllers\FavouriteStreamController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\JackpotTrackerController;
use App\Http\Controllers\LotteryJackpotTrackerController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\TermsAndConditionsController;

use App\Http\Controllers\Dashboard\PostController;
use App\Http\Controllers\Dashboard\CategoryController;
use App\Http\Controllers\Dashboard\StreamController;
use App\Http\Controllers\Dashboard\CasinoController;
use App\Http\Controllers\Dashboard\SlotController;
use App\Http\Controllers\Dashboard\JackpotController;
use App\Http\Controllers\Dashboard\CKEditorController;
use App\Http\Controllers\Dashboard\CommentController;
use App\Http\Controllers\Dashboard\AttachmentController;
use App\Http\Controllers\Dashboard\UserController;

use App\Http\Controllers\Auth\AdminLoginController;
use App\Http\Controllers\Auth\LoginController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['verify' => true]);

Route::get('/', [ShowPostController::class, 'index'])->name('home');

// SHOW SINGLE POST
Route::get('post/{slug}', [ShowPostController::class, 'show'])->name('posts.show');

Route::get('streams', [ShowStreamController::class, 'index'])->name('all-streams');
// SHOW SINGLE STREAM
Route::get('stream/{slug}', [ShowStreamController::class, 'show'])->name('streams.show');

// SORTING ROUTS
Route::get('/sortby/{type}/{ascendance}', [ShowPostController::class, 'sortby'])->where(['type' => '[a-z]+', 'ascendance' => '[a-z]+'])->name('posts.sortby');
Route::get('posts/category/{slug}', [ShowPostController::class, 'category'])->name('posts.category');
Route::get('posts/category/{slug}/sortby/{type}/{ascendance}', [ShowPostController::class, 'category_sortby'])->where(['type' => '[a-z]+', 'ascendance' => '[a-z]+'])->name('posts.category.sortby');
Route::get('streams/category/{slug}', [ShowStreamController::class, 'category'])->name('streams.category');

Route::middleware(['verified'])->prefix('favourite')->group(function() {
    Route::get('posts', [FavouritePostController::class, 'index'])->name('favourite.posts.index');
    Route::get('streams', [FavouriteStreamController::class, 'index'])->name('favourite.streams.index');
    Route::post('/save/post/{postid}', [FavouritePostController::class, 'store'])->name('favourite.posts.store');
    Route::post('/save/stream/{postid}', [FavouriteStreamController::class, 'store'])->name('favourite.streams.store');
    Route::post('/destroy/post/{postid}', [FavouritePostController::class, 'destroy'])->name('favourite.posts.destroy');
    Route::post('/destroy/stream/{postid}', [FavouriteStreamController::class, 'destroy'])->name('favourite.streams.destroy');
});

Route::prefix('admin')->group(function() {
    Route::get('/',[AdminLoginController::class, 'showLoginForm'])->name('admin.login');
    Route::post('login', [AdminLoginController::class, 'login'])->name('admin.login.submit');
    Route::post('logout', [AdminLoginController::class, 'logout'])->name('admin.logout');
});

Route::get('/profile', [ProfileController::class, 'index'])->name('profile');

Route::get('/jackpots-tracker', [JackpotTrackerController::class, 'index'])->name('jackpots-tracker');
Route::get('/lottery-tracker', [LotteryJackpotTrackerController::class, 'index'])->name('lottery-tracker');
Route::get('/lottery-tracker/{name}', [LotteryJackpotTrackerController::class, 'sortByName'])->name('lottery-name');

Route::get('/casinos', [ShowCasinoController::class, 'index'])->name('all-casinos');
Route::get('/casinos/{casino:slug}', [ShowCasinoController::class, 'show'])->name('casinos.show');

Route::get('search', [SearchController::class, 'search'])->name('search');

Route::prefix('contact')->group(function(){
    Route::get('/', [ContactController::class, 'index'])->name('contact');
    Route::post('submit', [ContactController::class, 'submitForm'])->name('submit-form');
});

// DASHBOARD START
Route::prefix('dashboard')->group(function(){
    Route::get('/', [PostController::class, 'index'])->name('dashboard');
    
    Route::resource('posts', PostController::class)->except([
        'index', 'show'
    ]);
    
    // Categories
    Route::resource('categories', CategoryController::class)->except([
        'edit', 'show', 'create'
    ]);

    // Streams    
    Route::resource('streams', StreamController::class)->except([
        'show'
    ]);
    
    // Casinos
    Route::resource('casinos', CasinoController::class)->except([
        'show'
    ]);

    // Slots
    Route::resource('slots', SlotController::class)->except([
        'edit', 'show'
    ]);
    Route::post('/slots/set-active/{slot}', [SlotController::class, 'setActive'])->name('slots.set-active');
    Route::post('/slots/{id}/{casinoid}', [SlotController::class, 'detach'])->name('slots.detach');

    //Jackpots
    Route::resource('jackpots', JackpotController::class)->except([
        'edit', 'show'
    ]);

    Route::post('upload', [CKEditorController::class, 'upload']);

    // approve comments
    Route::get('comments', [CommentController::class, 'index'])->name('dashboard.comments.index');
    Route::post('comments/{id}', [CommentController::class, 'approve'])->name('dashboard.comments.approve');
    Route::post('comments/destroy/{id}', [CommentController::class, 'destroy'])->name('dashboard.comments.destroy');

    // attachments
    Route::resource('attachments', AttachmentController::class)->only([
        'index', 'destroy'
    ]); 

    // users
    Route::resource('users', UserController::class)->only([
        'index', 'destroy'
    ]);
});
// DASHBOARD END

// LOGIN WITH GOOGLE FACEBOOK START
Route::prefix('login')->group(function(){
    Route::get('googleredirect', [LoginController::class, 'redirectToGoogleProvider'])->name('google.login');
    Route::get('googlecallback', [LoginController::class, 'handleGoogleProviderCallback']);

    Route::get('facebookredirect', [LoginController::class, 'redirectToFacebookProvider'])->name('facebook.login');
    Route::get('facebookcallback', [LoginController::class, 'handleFacebookProviderCallback']);
});
// LOGIN WITH GOOGLE FACEBOOK END

// TERMS

Route::get('/terms-and-conditions', [TermsAndConditionsController::class, 'index'])->name('terms');
Route::get('/about', [AboutController::class, 'index'])->name('about');

app/Http/Controllers/Dashboard/AttachmentController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Controllers\Dashboard\X;
use App\Attachment;
use App\Post;
use App\Category;
use App\Stream;
use App\Slot;
use App\Jackpot;
use App\Casino;
use Laravelista\Comments\Comment;

use App\Http\Traits\RemoveImage;

class AttachmentController extends Controller
{
    use RemoveImage;

    public function __construct()
    {
        $this->middleware('auth:admin');
        $this->per_page = 54;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $attachments = Attachment::orderBy('created_at', 'desc')->paginate($this->per_page);
        $total_posts = Post::all()->count();
        $total_streams = Stream::all()->count();
        $unapproved_comments = Comment::where('approved', false)->count();
        $total_categories = Category::all()->count();
        $total_slots = Slot::all()->count();
        $total_jackpots = Jackpot::all()->count();
        $total_casinos = Casino::all()->count();

        return view('dashboard.attachment', [
                'attachments' => $attachments,
                'total_categories' => $total_categories,
                'total_posts' => $total_posts,
                'total_streams' => $total_streams,
                'filemanager' => true,
                'unapproved_comments' => $unapproved_comments,
                'total_slots' => $total_slots,
                'total_jackpots' => $total_jackpots,
                'total_casinos' => $total_casinos,
            ]
        );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store($images_arr)
    {
        $attachment = new Attachment; 
        $attachment->image = $images_arr;
        $attachment->save();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Attachment  $attachment
     * @return \Illuminate\Http\Response
     */
    public function destroy(Attachment $attachment)
    {    
        $attachment_id = $attachment->id;

        $this->remove_image($attachment->image);

        Attachment::destroy($attachment->id);
        
        return redirect()->route('attachments.index')->with('success', "Attachment with id:{$attachment_id} removed!");
    }
}

app/Http/Controllers/Dashboard/CKEditorController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Storage;
use App\Http\Controllers\Dashboard\AttachmentController;

class CKEditorController extends Controller
{
    protected $images_arr_for_db;
    protected $attachment_controller;
    
    public function __construct(AttachmentController $attachment_controller)
    {
        $this->middleware('auth:admin');
        $this->images_arr_for_db = [];
        $this->attachment_controller = $attachment_controller;
    }

    public function upload(Request $request)
    {
        $this->validate($request, [
            'upload' => 'image|mimes:jpeg,jpg,png,gif,webp'
        ]);

        if ($request->hasFile('upload')) {

            $sub_folder_n = date('n-Y');
            $post_image = $request->file('upload');

            $images_arr = $this->save_post_content_images($post_image, $sub_folder_n);

        } else {
            return json_encode(
                [
                    'error' => [
                        'message' => 'There is no file to upload'
                    ],
                ]
            );
        }

        return json_encode(
            [
                'urls' => $images_arr
            ]
        );
    }

    private function save_post_content_images($image, string $folder)
    {
        $file = str_slug(pathinfo($image->getClientOriginalName())['filename'], '-');
        $folder1 = trim($folder);
        $file_path = "post-images/{$folder1}/";

        $lg_image_width;
        $md_image_width; 
        $sm_image_width;

        $img_lg = Image::make($image)->encode('webp', 40);
        
        $img_lg->resize(1600, null, function ($constraint) {
            $constraint->aspectRatio();
            $constraint->upsize();
        });
        
        $lg_image_width = $img_lg->width();

        if ( $lg_image_width <= 1600 && $lg_image_width > 836 ) {

            $lg_image_path = $file_path . "{$file}-{$lg_image_width}w-lg.webp";

            Storage::disk('s3')->put($lg_image_path, $img_lg->stream());
            Storage::disk('s3')->setVisibility($lg_image_path, 'public');
            
            $images_arr[$lg_image_width] = Storage::disk('s3')->url($lg_image_path);

        }

        $img_md = $img_lg->resize(836, null, function ($constraint) {
            $constraint->aspectRatio();
            $constraint->upsize();
        });
        $md_image_width = $img_md->width();

        if ( $md_image_width <= 836 && $md_image_width > 400 ) {

            $md_image_path = $file_path . "{$file}-{$md_image_width}w-md.webp";

            Storage::disk('s3')->put($md_image_path, $img_md->stream());
            Storage::disk('s3')->setVisibility($md_image_path, 'public');
            
            $images_arr[$md_image_width] = Storage::disk('s3')->url($md_image_path);

        }
            
        $img_sm = $img_md->resize(400, null, function ($constraint) {
            $constraint->aspectRatio();
            $constraint->upsize();
        });
        $sm_image_width = $img_sm->width();

        if ( $sm_image_width <= 400 ) {
 
            $sm_image_path = $file_path . "{$file}-{$sm_image_width}w-sm.webp";
            
            Storage::disk('s3')->put($sm_image_path, $img_sm->stream());
            Storage::disk('s3')->setVisibility($sm_image_path, 'public');

            $images_arr[$sm_image_width] = Storage::disk('s3')->url($sm_image_path);

        }
        
        $images_arr['default'] = isset($lg_image_path) ? Storage::disk('s3')->url($lg_image_path) : (isset($md_image_path) ? Storage::disk('s3')->url($md_image_path) : Storage::disk('s3')->url($sm_image_path));
        
        // prepare image array for storing in the database start

        $images = $images_arr;
        unset($images['default']);
        $images = array_values($images);
        $this->images_arr_for_db = $images;

        // prepare image array for storing in the database end
        
        // store image array in data base
        $this->add_images_to_db();
        
        $img_lg = null;

        return $images_arr;
    }

    public function add_images_to_db()
    {
        if ( !empty($this->images_arr_for_db) ) {
            $this->attachment_controller->store($this->images_arr_for_db);
        }
    } 
}
 

app/Http/Controllers/Dashboard/CommentController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Config;
use DB;
use Illuminate\Http\Request;

use App\User;
use App\Post;
use App\Category;
use App\Stream;
use App\Slot;
use App\Jackpot;
use App\Casino;
use Laravelista\Comments\Comment;

class CommentController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
        $this->per_page = 20;
    }

    public function index()
    {  
        $comments = DB::table('comments')
            ->leftJoin('users', 'users.id', '=', 'comments.commenter_id')
            ->select(['comments.commenter_id', 'comments.comment', 'comments.approved', 'comments.commenter_type', 'comments.created_at', 'comments.id', 'comments.guest_name', 'users.name'])
            ->orderBy('comments.approved', 'asc')->orderBy('comments.created_at', 'desc')
            ->paginate($this->per_page);

        $categories = Category::orderBy('name', 'asc')->get();
        $total_categories = Category::all()->count();
        $total_posts = Post::all()->count();
        $total_streams = Stream::all()->count();
        $unapproved_comments = Comment::where('approved', false)->count();
        $total_slots = Slot::all()->count();
        $total_jackpots = Jackpot::all()->count();
        $total_casinos = Casino::all()->count();

        return view('dashboard.comments', [
                'categories' => $categories,
                'total_categories' => $total_categories,
                'total_posts' => $total_posts,
                'total_streams' => $total_streams,
                'comments' => $comments,
                'unapproved_comments' => $unapproved_comments,
                'total_slots' => $total_slots,
                'total_jackpots' => $total_jackpots,
                'total_casinos' => $total_casinos,
            ]
        );
    }

    public function approve($id)
    {
        $comment = Comment::find($id);
        $comment->approved = true;
        $comment->save();
        return redirect()->back()->with('success', 'Comment was approved');
    }

    public function destroy($id)
    {
        $comment = Comment::find($id);
        
        if (Config::get('comments.soft_deletes') == true) {
			$comment->delete();
		}
		else {
			$comment->forceDelete();
        }
        
        return redirect()->back()->with('success', 'Comment was removed');
    }
}

resources/views/dashboard/inc/sidebar_menu.blade.php
<div class="column col-4 col-md-12 dashboard_sidebar">
    <ul class="menu">
        <!-- menu header text -->
        <li class="divider" data-content="MENU"></li>
        <!-- menu item standard -->
        <li class="menu-item">
            <a href="{{ route('dashboard') }}">
                Articles
            </a>  
            <div class="menu-badge">
                <label class="label label-primary">{{ $total_posts ?? 0 }}</label>
            </div>
        </li>
        <li class="menu-item">
            <a href="{{ route('streams.index') }}">
                Streams 
            </a>        
            <div class="menu-badge">
                <label class="label label-primary">{{ $total_streams ?? 0 }}</label>
            </div>        
        </li>
        <li class="menu-item">
            <a href="{{ route('categories.index') }}">
                Categories
            </a>
            <div class="menu-badge">
                <label class="label label-primary">{{ $total_categories ?? 0 }}</label>
            </div>
        </li>
        <li class="menu-item">
            <a href="{{ route('dashboard.comments.index') }}">
                Comments
            </a>
            <div class="menu-badge">
                <label class="label label-primary">{{ $unapproved_comments ?? 0 }}</label>
            </div>
        </li>    
        <li class="menu-item">
            <a href="{{ route('casinos.index') }}">
                Casinos
            </a>
            <div class="menu-badge">
                <label class="label label-primary">{{ $total_casinos ?? 0 }}</label>
            </div>
        </li>
        <li class="menu-item">
            <a href="{{ route('slots.index') }}">
                Slots
            </a>
            <div class="menu-badge">
                <label class="label label-primary">{{ $total_slots ?? 0 }}</label>
            </div>
        </li>
        <li class="menu-item">
            <a href="{{ route('jackpots.index') }}">
                Slot Jackpots
            </a>
            <div class="menu-badge">
                <label class="label label-primary">{{ $total_jackpots ?? 0 }}</label>
            </div>
        </li>
        <li class="menu-item">
            <a href="{{ route('attachments.index') }}">
                Attachments
            </a>
        </li>
        <li class="menu-item">
            <a href="{{ route('users.index') }}">
                Users
            </a>
        </li>
    </ul>
</div>

resources/views/dashboard/inc/wide_sidebar_menu.blade.php
<div class="column col-12 dashboard_sidebar file_manager_menu">
    <ul class="menu">
        <!-- menu header text -->
        <li class="divider" data-content="MENU"></li>
        <!-- menu item standard -->
        <li class="menu-item">
            <a href="{{ route('dashboard') }}">
                Articles
            </a>  
            <div class="menu-badge">
                <label class="label label-primary">{{ $total_posts ?? 0 }}</label>
            </div>
        </li>
        <li class="menu-item">
            <a href="{{ route('streams.index') }}">
                Streams 
            </a>        
            <div class="menu-badge">
                <label class="label label-primary">{{ $total_streams ?? 0 }}</label>
            </div>        
        </li>
        <li class="menu-item">
            <a href="{{ route('categories.index') }}">
                Categories
            </a>
            <div class="menu-badge">
                <label class="label label-primary">{{ $total_categories ?? 0 }}</label>
            </div>
        </li>
        <li class="menu-item">
            <a href="{{ route('dashboard.comments.index') }}">
                Comments
            </a>
            <div class="menu-badge">
                <label class="label label-primary">{{ $unapproved_comments ?? 0 }}</label>
            </div>
        </li>    
        <li class="menu-item">
            <a href="{{ route('casinos.index') }}">
                Casinos
            </a>
            <div class="menu-badge">
                <label class="label label-primary">{{ $total_casinos ?? 0 }}</label>
            </div>
        </li>
        <li class="menu-item">
            <a href="{{ route('slots.index') }}">
                Slots
            </a>
            <div class="menu-badge">
                <label class="label label-primary">{{ $total_slots ?? 0 }}</label>
            </div>
        </li>
        <li class="menu-item">
            <a href="{{ route('jackpots.index') }}">
                Slot Jackpots
            </a>
            <div class="menu-badge">
                <label class="label label-primary">{{ $total_jackpots ?? 0 }}</label>
            </div>
        </li>
        <li class="menu-item">
            <a href="{{ route('attachments.index') }}">
                Attachments
            </a>
        </li>
        <li class="menu-item">
            <a href="{{ route('users.index') }}">
                Users
            </a>
        </li>
    </ul>
</div>